name: Travis Bai's Blog
description: Life Love Dream
meta_description: "Travis Bai New Jekyll Site, Blogging about life love and dream"

aboutPage: true

markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]

paginate: 20
baseurl: /
domain_name: 'http://www.travisbai.me'
google_analytics: 'UA-66074546-1'
disqus: true
disqus_shortname: 'travisbaiblog'

# Details for the RSS feed generator
url:            'http://www.travisbai.me'
author:         'Travis Bai'
authorTwitter:  'travisbai'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
